# Generated by Django 2.1.12 on 2023-12-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents', models.TextField(verbose_name='讨论区内容')),
            ],
        ),
        migrations.CreateModel(
            name='problem_solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='题目名字')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlename', models.CharField(max_length=45, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('type', models.IntegerField(verbose_name='题目类别')),
                ('background', models.CharField(max_length=45, verbose_name='题目背景')),
                ('solution', models.TextField(verbose_name='题解')),
            ],
        ),
        migrations.CreateModel(
            name='teaminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=45, verbose_name='队伍名字')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='队伍分数')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='队伍排名')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14, verbose_name='用户名')),
                ('password', models.CharField(max_length=25, verbose_name='用户密码')),
                ('name', models.CharField(max_length=14, verbose_name='姓名')),
                ('selfintroduction', models.TextField(blank=True, null=True, verbose_name='自我介绍')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像')),
                ('solved_problem', models.IntegerField(blank=True, default=0, null=True, verbose_name='通过题目数')),
                ('is_admin', models.IntegerField(default=0, verbose_name='是否为管理员')),
                ('ranknum', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('qq', models.CharField(blank=True, max_length=13, null=True, verbose_name='qq')),
                ('gender', models.CharField(max_length=11, verbose_name='性别')),
                ('age', models.CharField(max_length=12, verbose_name='年龄')),
                ('major', models.CharField(max_length=12, verbose_name='专业')),
                ('github', models.CharField(blank=True, max_length=120, null=True, verbose_name='github主页')),
                ('blog', models.CharField(blank=True, max_length=120, null=True, verbose_name='博客主页')),
                ('mail', models.CharField(blank=True, max_length=120, null=True, verbose_name='邮箱地址')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.teaminfo')),
            ],
        ),
        migrations.AddField(
            model_name='problem_solved',
            name='solved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.teaminfo'),
        ),
        migrations.AddField(
            model_name='problem_solved',
            name='solver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.userinfo'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussionPr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.question', verbose_name='题目id'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.userinfo', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.discussion', verbose_name='回复的讨论区id'),
        ),
    ]
