# Generated by Django 2.1.12 on 2023-12-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem_collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.question')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.userinfo')),
            ],
        ),
    ]
