# Generated by Django 2.1.12 on 2023-12-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20231210_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='titlename',
            new_name='name',
        ),
    ]
