# Generated by Django 2.1.12 on 2023-12-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20231210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_solved',
            name='solved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.question'),
        ),
    ]
