# Generated by Django 2.1.12 on 2023-12-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20231217_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminfo',
            options={'ordering': ('-score', 'id')},
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛1'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score10',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛10'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛2'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛3'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛4'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score5',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛5'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score6',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛6'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score7',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛7'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score8',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛8'),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='score9',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='比赛9'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='队伍分数'),
        ),
    ]
